### ISSUE TITLE
Create tags for major stable releases?

### ISSUE THREAD

**Issue by jiawen** [RLovelett/eigen#6]
I recently discovered this rather excellent GitHub mirror for Eigen. I am aware of the complexity mentioned in [Issue 3](https://github.com/RLovelett/eigen/issues/3), but would it be possible to manually tag Eigen's major releases? Looking at the Eigen homepage, there have only been 5 major releases since April 2016.

**Comment by mserdarsanli** [comment]
+1 to this

In Eigen homepage, there is an announcement for Eigen 3.3.2 release dated 18.01.2017, but the latest tagged release in this repo is [3.1.2](https://github.com/RLovelett/eigen/releases/tag/3.1.2) which is 4+ years old.

**Comment by RLovelett** [comment]
[As I've said before](https://github.com/RLovelett/eigen/issues/3#issuecomment-190933132) I'm not against these requests. They are reasonable and justifiable. I've provided [the code](https://github.com/RLovelett/eigen/issues/3#issuecomment-130808839) that runs on the server to perform the mirroring. If you provide code to provide tags I'd be happy to run it on the server that provides the mirror.

I'm just not going to do it myself because I don't know how to do it. I'm not interested in working on it because I don't even use Eigen anymore.

Frankly the only reason why I haven't deleted this repo and shutdown the mirror script is because it appears to provide a little bit of value to others.

I don't think I'm being unreasonable to ask the community that would derive value from it to help provide the capability they're requesting.

**Comment by mserdarsanli** [comment]
After a few hours of trying various tools, including hg-git, github importer etc. I found that only git-remote-hg is able to handle the Eigen repo.

Its usage is like this

    git clone hg::https://bitbucket.org/eigen/eigen
    git remote add Github https://github.com/mserdarsanli/eigen-git-mirror.git
    git push Github --all
    git push Github --tags

This handles the tags as well, as you can see in the repo I created here https://github.com/mserdarsanli/eigen-git-mirror/releases

And `git-remote-hg` seems to be in Debian repositories, so setting it up only requires an

    apt-get install git-remote-hg

As I have no experience with Jenkins, I can not help you update your script, and I don't plan to keep my repo synced daily.

**Comment by RLovelett** [comment]
@mserdarsanli THANK YOU! I will try and get this setup ASAP.

**Comment by jiawen** [comment]
@mserdarsanli Whoa, that's awesome! Thanks for all your hard work!

**Comment by RLovelett** [comment]
Ok I think this is working now. It looks like we have branches and tags. This is the command that runs on Jenkins now.

```
git rev-parse --is-inside-git-dir || git clone --mirror hg::https://bitbucket.org/eigen/eigen .
git remote update
git push --mirror git@github.com:RLovelett/eigen.git
```
